//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClothShopManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailsId { get; set; }
        public int OrderId { get; set; }
        public int ProductCategoryId { get; set; }
        public int ProductId { get; set; }
        public int OrderQuantity { get; set; }
        public string OrderUnit { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Product Product { get; set; }
    }
}
